/**
 * Install Agents MD command - Generate and append CLI usage instructions to AGENTS.md
 */

import { readFile, writeFile, access } from "fs/promises";
import { resolve, join } from "path";
import type { CommandContext } from "../cli/types.js";
import { Command } from "commander";

interface InstallAgentsMdOptions {
  file?: string;
  workingDir?: string;
  force?: boolean;
}

/**
 * Check if a command exists in the Commander.js program
 */
function commandExists(program: Command, commandName: string): boolean {
  try {
    const commands = program.commands || [];
    return commands.some((cmd) => {
      const name = typeof cmd.name === "function" ? cmd.name() : cmd.name;
      return name === commandName;
    });
  } catch {
    return false;
  }
}

/**
 * Check if a command has a specific option
 */
function commandHasOption(
  program: Command,
  commandName: string,
  optionName: string
): boolean {
  try {
    const commands = program.commands || [];
    const cmd = commands.find((cmd) => {
      const name = typeof cmd.name === "function" ? cmd.name() : cmd.name;
      return name === commandName;
    });

    if (!cmd) return false;

    // Check if option exists by looking at options
    const options = (cmd as any).options || [];
    return options.some((opt: any) => {
      const long = opt.long || "";
      const short = opt.short || "";
      // Check for exact match or if option name appears in the option string
      // e.g., "--plan <file>" should match "plan"
      return (
        long === `--${optionName}` ||
        short === `-${optionName}` ||
        long.includes(`--${optionName}`) ||
        long.includes(`<${optionName}>`) ||
        long.toLowerCase().includes(optionName.toLowerCase())
      );
    });
  } catch {
    return false;
  }
}

/**
 * Generate CLI usage instructions based on available commands
 */
function generateInstructions(program: Command): string {
  let content = `## CLI Usage for AI Agents

This section is auto-generated by \`install-agents-md\` command.

## How to Think About Making Plans

When creating plans for cloud agents, follow these principles:

### Plan Structure

A good plan should include:

1. **Clear Goals** - What are you trying to accomplish?
2. **Specific Tasks** - Break down the work into concrete, actionable steps
3. **File Changes** - List which files will be created, modified, or deleted
4. **Expected Outcome** - What should the result look like?

### Example Good Plan:

\`\`\`markdown
# Add User Authentication

## Goals
- Add login/logout functionality
- Protect routes that require authentication
- Store user sessions securely

## Tasks
- Create \`src/auth/login.tsx\` (new file)
- Create \`src/auth/logout.tsx\` (new file)
- Update \`src/routes.tsx\` (add auth middleware)
- Update \`src/components/Header.tsx\` (add login/logout buttons)

## Expected Outcome
- Users can log in and log out
- Protected routes redirect to login if not authenticated
- Session persists across page refreshes
\`\`\`

### Parallelization Rules

**CRITICAL:** Only launch tasks that are **strictly parallel** - meaning they modify completely different files with zero overlap.

**Can run in parallel:**
- Plans that modify completely different files (no file overlap)
- Plans that create new files without modifying any existing files
- Plans with zero shared dependencies

**CANNOT run in parallel:**
- Multiple plans modifying the same file (even different functions/lines)
- Plans that modify different parts of the same file
- Plans that create new files but also modify a shared existing file
- Plans with any shared file dependencies
- Plans that depend on outputs from other plans

**For same-file refactorings:** Use a phased approach - launch Phase 1, wait for completion, then launch Phase 2.

## How to Kick Off Plans

`;

  // Check launch command
  if (commandExists(program, "launch")) {
    content += `### Launch Command

Launch an agent from a plan file:

\`\`\`bash
bun run cloud-agent.tsx launch --plan <plan-file>
\`\`\`

`;

    if (commandHasOption(program, "launch", "plan")) {
      content += `**Required:** \`--plan <file>\` - Plan file path or \`-\` for stdin

`;
    }

    if (commandHasOption(program, "launch", "model")) {
      content += `**Optional:** \`--model <name>\` - Override auto-selected model (composer-1 or claude-4.5-opus-high)

`;
    }

    if (commandHasOption(program, "launch", "repo")) {
      content += `**Optional:** \`--repo <url>\` - Repository URL (auto-detected from git if not provided)

`;
    }

    if (commandHasOption(program, "launch", "ref")) {
      content += `**Optional:** \`--ref <ref>\` - Git ref (auto-detected from git if not provided)

`;
    }

    if (commandHasOption(program, "launch", "verbose")) {
      content += `**Optional:** \`--verbose\` or \`-v\` - Show verbose output

`;
    }

    content += `**Output:** Agent URL (e.g., \`https://cursor.com/agents?id=bc_abc123\`)
**Exit code:** 0 on success, 1 on error

**Example workflow:**

\`\`\`bash
# Launch agent from plan file
AGENT_ID=$(bun run cloud-agent.tsx launch --plan plan/feature-auth.md)

# Watch until completion
bun run cloud-agent.tsx watch $AGENT_ID --verbose

# Check if successful (exit code 0 = success)
if [ $? -eq 0 ]; then
  echo "Agent completed successfully!"
else
  echo "Agent failed or was cancelled"
fi
\`\`\`

`;
  }

  // Check watch command
  if (commandExists(program, "watch")) {
    content += `### Watch Command

Watch agent(s) until completion:

\`\`\`bash
# Single agent
bun run cloud-agent.tsx watch <agent-id> --verbose

# Multiple agents
bun run cloud-agent.tsx watch <agent-id-1> <agent-id-2> --verbose
\`\`\`

**Exit code:** 0 if all finished successfully, 1 if any failed/cancelled

`;
  }

  // Check list command
  if (commandExists(program, "list")) {
    content += `### List Command

List agents (non-interactive mode required for AI agents):

\`\`\`bash
bun run cloud-agent.tsx list --non-interactive

# With search
bun run cloud-agent.tsx list --non-interactive --search "refactor"
\`\`\`

**CRITICAL:** Always use \`--non-interactive\` flag for AI agents

`;
  }

  // Check status command
  if (commandExists(program, "status")) {
    content += `### Status Command

Check agent status (non-interactive mode required):

\`\`\`bash
bun run cloud-agent.tsx status <agent-id> --non-interactive
\`\`\`

**CRITICAL:** Always use \`--non-interactive\` flag for AI agents

`;
  }

  // Check followup command
  if (commandExists(program, "followup")) {
    content += `### Followup Command

Add follow-up instructions to a running agent:

\`\`\`bash
bun run cloud-agent.tsx followup <agent-id> "Please add tests"
\`\`\`

`;
  }

  // Check conversation command
  if (commandExists(program, "conversation")) {
    content += `### Conversation Command

View agent conversation (non-interactive mode required):

\`\`\`bash
bun run cloud-agent.tsx conversation <agent-id> --non-interactive
\`\`\`

`;
  }

  // Check batch-delete command
  if (commandExists(program, "batch-delete")) {
    content += `### Batch Delete Command

Delete multiple agents:

\`\`\`bash
bun run cloud-agent.tsx batch-delete --status FINISHED --force
\`\`\`

**Status options:** FINISHED, FAILED, CANCELLED, CREATING, RUNNING, or 'terminal'

`;
  }

  content += `### Important Notes for AI Agents

1. **Always use \`--non-interactive\`** for \`list\`, \`status\`, and \`conversation\` commands
2. **Parallelization:** Only launch tasks that modify completely different files
3. **Model selection:** Auto-selected based on plan content, override with \`--model\` if needed
4. **Exit codes:** Use exit codes to determine success (0) or failure (1)
5. **Plan files:** Store plans in \`plan/\` directory for organization
6. **Wait for completion:** Use \`watch\` command to block until agents finish

`;

  return content;
}

/**
 * Check if launch --plan command instructions already exist in content
 */
function hasLaunchCommandInstructions(content: string): boolean {
  // Simple check: look for "launch --plan" pattern
  return content.includes("launch --plan");
}

export async function executeInstallAgentsMd(
  context: CommandContext,
  options: InstallAgentsMdOptions
): Promise<void> {
  const { workingDir } = context;
  const targetFile = options.file || "AGENTS.md";
  const workingDirectory = options.workingDir || workingDir;

  try {
    // Resolve the target file path
    const filePath = resolve(workingDirectory, targetFile);

    // Check if file exists
    let fileExists = false;
    try {
      await access(filePath);
      fileExists = true;
    } catch {
      fileExists = false;
    }

    // Read existing content or start with empty string
    let existingContent = "";
    if (fileExists) {
      existingContent = await readFile(filePath, "utf-8");
    }

    // Check if launch command instructions already exist (unless --force is used)
    if (!options.force && hasLaunchCommandInstructions(existingContent)) {
      console.log(`✓ ${targetFile} already contains CLI usage instructions`);
      console.log(`  Skipping installation to prevent duplicates.`);
      console.log(`  Use --force to overwrite existing instructions.`);
      return;
    }

    // Create a temporary Commander.js program to check commands
    const { Command } = await import("commander");
    const program = new Command();
    const { registerCommands } = await import("./index.js");
    registerCommands(program, context);

    // Generate new instructions
    const newInstructions = generateInstructions(program);

    // Check if section already exists (even without launch instructions)
    const sectionMarker = "## CLI Usage for AI Agents";
    if (existingContent.includes(sectionMarker)) {
      // Find the section and replace it
      const sectionStart = existingContent.indexOf(sectionMarker);
      const nextSectionMatch = existingContent
        .slice(sectionStart + sectionMarker.length)
        .match(/^## /m);
      const sectionEnd = nextSectionMatch
        ? sectionStart +
          sectionMarker.length +
          existingContent
            .slice(sectionStart + sectionMarker.length)
            .indexOf(nextSectionMatch[0])
        : existingContent.length;

      const beforeSection = existingContent.slice(0, sectionStart);
      const afterSection = existingContent.slice(sectionEnd);

      // Reconstruct content with updated section
      const updatedContent =
        beforeSection +
        newInstructions +
        (afterSection ? "\n" + afterSection : "");

      await writeFile(filePath, updatedContent, "utf-8");
      console.log(`✓ Updated ${targetFile} with latest CLI usage instructions`);
    } else {
      // Append new section
      const updatedContent =
        existingContent +
        (existingContent && !existingContent.endsWith("\n") ? "\n" : "") +
        "\n" +
        newInstructions;

      await writeFile(filePath, updatedContent, "utf-8");
      console.log(`✓ Added CLI usage instructions to ${targetFile}`);
    }
  } catch (error) {
    if (error instanceof Error) {
      console.error(`Error: ${error.message}`);
    } else {
      console.error("Error: Failed to install agents.md instructions");
    }
    process.exit(1);
  }
}
